name: CI Production

on:
  push:
    tags:
      - "releases/[0-9]*.[0-9]*.[0-9]*"
    
jobs:

  job:
    name: Test and Release

    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    steps:
    
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry and setup cache
        uses: Gr1N/setup-poetry@v2
      
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-3.8-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-3.8-
      
      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build
      
      - name: Release
        run: poetry publish -u __token__ -p "${PYPI_TOKEN}"
