# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Based on https://github.com/actions/starter-workflows

name: Development Test

on:
  push:
    branches: 
      - dev

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    
    - name: Checkout repositry
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
     
    - name: Install dependencies and package
      run: |
        pip3 install -r requirements-dev.txt
        python setup.py develop 
        
    - name: Lint with flake8
      run: |
        flake8 --config .flake8 --statistics
        
    - name: Test with pytest
      run: |
        pytest
