name: release

on:
  release:
    types:
      - published
    
jobs:

  test:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    
    - name: Checkout repositry
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v2
    
    - name: Install dependencies
      run: poetry install
    
    - name: Lint with flake8
      run: poetry run flake8 --config .flake8 --statistics

    - name: Run Pytest
      run: poetry run pytest --cov=./ --cov-report=xml

    - name: Run Pytest multiprocess
      run: |
        mkdir -p /tmp/test_multiproc
        export prometheus_multiproc_dir=/tmp/test_multiproc
        poetry run pytest -k test_multiprocess_reg --cov-append --cov=./ --cov-report=xml
        rm -rf /tmp/test_multiproc
        unset prometheus_multiproc_dir

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      if: matrix.python-version == 3.8
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Run black formatter
      run: poetry run black .

    - name: Recommit black format
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply black format [skip ci]
        file_pattern: ./*.py
        commit_user_name: My GitHub Actions Bot
        commit_user_email: tim.schwenke+github@protonmail.ch

    - name: Build package
      run: poetry build

  release:
    needs: test
    
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    steps:
    
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry and setup cache
        uses: Gr1N/setup-poetry@v2
      
      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build
      
      - name: Release
        run: poetry publish -u __token__ -p "${PYPI_TOKEN}"
